from classes import *
player = Character(name=input("Enter your character's name: "), character_class=input("Enter your character's class: "), inventory=Inventory(capacity=1))
inventory = Inventory(player, capacity=1)
player.inventory = inventory
NPC = QuestGiver(name="NPC", available_quests=quests)
NPC.give_quest(player)
player.inventory.add_item(Weapon(name="Sword", description="A basic sword.", quality="Common", damage=500.0))
player.equip_weapon(Weapon(name="Sword", description="A basic sword.", quality="Common", damage=500.0))
player.attack(mob4)
player.attack(mob4)
print(player.inventory.contents)
print()
print(player.storage.contents)
player.storage.add_item(Weapon(name="Sword", description="A basic sword.", quality="Common", damage=500.0))
player.storage.add_item(Weapon(name="Sword", description="A basic sword.", quality="Common", damage=500.0))
player.inventory.remove_item(Weapon(name="Sword", description="A basic sword.", quality="Common", damage=500.0))
player.inventory.take_item_from_storage(Weapon(name="Sword", description="A basic sword.", quality="Common", damage=500.0))
player.inventory.take_item_from_storage(Weapon(name="Sword", description="A basic sword.", quality="Common", damage=500.0))
player.inventory.take_item_from_storage(Weapon(name="Sword", description="A basic sword.", quality="Common", damage=500.0))
player.inventory.take_item_from_storage(Weapon(name="Sword", description="A basic sword.", quality="Common", damage=50))
player.inventory.deposit_item_to_storage(Weapon(name="Sword", description="A basic sword.", quality="Common", damage=500.0))